### ISSUE TITLE
I don't think it works...

### ISSUE THREAD

**Issue by wuniversales** [omidmaroofi/freebitcoin-Auto_roll#8]
I have both possibilities, to use the captcha, or not to use it.
The case, it detects the balance well and others, but does not click on the button "No captcha" when the hour passes.

More information:
- I have the tab open (https://freebitco.in/?op=home) in firefox.
- I have the plugin activated (ON).
- I have "Fixed" the tab in firefox. (Maybe it's a problem with this?).

I will test without fixing the tab, to see if it works like this ...

Cheers

**Comment by omidmaroofi** [comment]
hi dear
This plugin does not work with Captcha code
First, your account must be without a captcha code so that this plugin works well
Use this link to download in Firefox
https://addons.mozilla.org/en-US/firefox/addon/freebitco-in-automated_roll/
good luck

**Comment by omidmaroofi** [comment]
> 
> 
> I have both possibilities, to use the captcha, or not to use it.
> The case, it detects the balance well and others, but does not click on the button "No captcha" when the hour passes.
> 
> More information:
> 
>     * I have the tab open (https://freebitco.in/?op=home) in firefox.
> 
>     * I have the plugin activated (ON).
> 
>     * I have "Fixed" the tab in firefox. (Maybe it's a problem with this?).
> 
> 
> I will test without fixing the tab, to see if it works like this ...
> 
> Cheers

hi dear
This plugin does not work with Captcha code
First, your account must be without a captcha code so that this plugin works well
Use this link to download in Firefox
https://addons.mozilla.org/en-US/firefox/addon/freebitco-in-automated_roll/
good luck

**Comment by omidmaroofi** [comment]
you should see it on the freebico tab
this plugin works well by going to any tab in Firefox
you can also minimize Firefox and do other things.
